apiVersion: apps/v1
kind: Deployment
metadata:
  name: mystudio-db
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1   
  selector:
    matchLabels:
      app: mystudio-db
  template:
    metadata:
      labels:
        app: mystudio-db
    spec:
      containers:
        - image: mysql
          imagePullPolicy: IfNotPresent
          name: mystudio-db
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: grippolek2022