name: watcher_client_dal
description: DAL layer of watcher client
version: 0.0.1

dependencies:
  flutter:
    sdk: flutter
  automap: 0.0.3
  get_it: 7.2.0
  freezed_annotation: ^2.0.1
  http: ^0.13.4

dev_dependencies:
  build_runner: ^2.1.10
  freezed: ^2.0.2
  json_serializable: ^6.2.0

environment:
  sdk: ">=2.15.1 <3.0.0"
