name: client_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.0.1
  event: ^2.1.2
  get_it: ^7.2.0
  http: ^0.13.4
  watcher_client_bll:
    path: packages/watcher_client_bll
  automap: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.10
  freezed: ^2.0.2

flutter:
  uses-material-design: true

analyzer:
  errors:
    invalid_annotation_target: ignore
